name: build_version
description: A builder for extracting a package version into code.
version: 2.1.0
homepage: https://github.com/kevmoo/build_version
author: Kevin Moore <kevmoo@google.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  build: '>=0.12.1 <2.0.0'
  # Not imported in code, but used to constrain `build.yaml` requirements
  build_config: ^0.3.0
  pubspec_parse: ^0.1.2+2

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.3+1
  build_verify: ^1.0.0
  pedantic: ^1.4.0
  test: ^1.2.0
