name: build_version
description: A builder for extracting a package version into code.
version: 2.0.2-dev
homepage: https://github.com/kevmoo/build_version
author: Kevin Moore <kevmoo@google.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  build: ^2.0.0
  # Not imported in code, but used to constrain `build.yaml` requirements
  build_config: '>=0.3.0 <0.5.0'
  pubspec_parse: ^1.0.0

dev_dependencies:
  build_runner: ^1.12.0
  build_test: ^2.0.0
  build_verify: ^1.0.0
  checked_yaml: ^2.0.0
  pedantic: ^1.4.0
  test: ^1.16.0
